import { QuizQuestion } from '@/types/learnai';

export const ALL_QUIZ_POOLS: Record<string, QuizQuestion[]> = {
  stack: [
    {
      id: 'q_stack_1',
      type: 'mcq',
      concept: 'Stack Principle',
      difficulty: 'Intermediate',
      question: 'Which principle governs how elements enter and leave a Stack data structure?',
      options: [
        'A) LIFO (Last-In, First-Out)',
        'B) FIFO (First-In, First-Out)',
        'C) Random Access Indexing',
        'D) Priority Key Queue',
      ],
      correctAnswer: 'A) LIFO (Last-In, First-Out)',
      explanation: 'Stacks operate on LIFO: the last element added is the first one removed — like a stack of plates.',
    },
    {
      id: 'q_stack_2',
      type: 'mcq',
      concept: 'Time Complexity',
      difficulty: 'Intermediate',
      question: 'What is the Time Complexity of push() and pop() operations in a Stack?',
      options: ['A) O(N) linear time', 'B) O(1) constant time', 'C) O(N log N)', 'D) O(N^2)'],
      correctAnswer: 'B) O(1) constant time',
      explanation: 'Both push() and pop() only interact with the top element of the stack, running in O(1) constant time.',
    },
    {
      id: 'q_stack_3',
      type: 'mcq',
      concept: 'Applications',
      difficulty: 'Intermediate',
      question: 'Which real-world software feature relies directly on a Stack data structure?',
      options: [
        'A) Text editor Undo/Redo mechanism (Ctrl+Z)',
        'B) Printer document queue',
        'C) Database indexing',
        'D) Round-robin CPU scheduling',
      ],
      correctAnswer: 'A) Text editor Undo/Redo mechanism (Ctrl+Z)',
      explanation: 'Text editors push actions onto a stack. Undo (Ctrl+Z) pops the most recent action off the top!',
    },
    {
      id: 'q_stack_4',
      type: 'mcq',
      concept: 'Error Handling',
      difficulty: 'Intermediate',
      question: 'What exception is raised if you pop() from an empty stack in Python?',
      options: [
        'A) IndexError: pop from empty list',
        'B) StackOverflowError',
        'C) KeyNotFoundException',
        'D) ZeroDivisionError',
      ],
      correctAnswer: 'A) IndexError: pop from empty list',
      explanation: 'Popping from an empty Python list raises an IndexError.',
    },
    {
      id: 'q_stack_5',
      type: 'mcq',
      concept: 'Operations',
      difficulty: 'Intermediate',
      question: 'What does the peek() or top() operation do on a Stack?',
      options: [
        'A) Deletes the entire stack',
        'B) Inspects the top item without removing it',
        'C) Reverses all items in the stack',
        'D) Sorts the stack elements',
      ],
      correctAnswer: 'B) Inspects the top item without removing it',
      explanation: 'peek() returns the value of the top element without popping it off the stack.',
    },
    {
      id: 'q_stack_6',
      type: 'mcq',
      concept: 'Call Stack',
      difficulty: 'Intermediate',
      question: 'In a function call stack during recursion, what happens when a function returns?',
      options: [
        'A) A new frame is pushed onto the stack',
        'B) The memory heap is cleared',
        'C) Its frame is popped off the top of the call stack',
        'D) Execution restarts from main',
      ],
      correctAnswer: 'C) Its frame is popped off the top of the call stack',
      explanation: 'When a function finishes execution, its stack frame is popped off the call stack.',
    },
    {
      id: 'q_stack_7',
      type: 'mcq',
      concept: 'Matching Brackets',
      difficulty: 'Intermediate',
      question: 'Which data structure is best suited to verify balanced parentheses like `(()[])`?',
      options: ['A) Queue', 'B) Stack', 'C) Binary Heap', 'D) Hash Table'],
      correctAnswer: 'B) Stack',
      explanation: 'Open brackets are pushed onto a stack. When a closing bracket appears, it must match the popped top bracket.',
    },
    {
      id: 'q_stack_8',
      type: 'mcq',
      concept: 'Stack vs Queue',
      difficulty: 'Intermediate',
      question: 'How does a Stack differ fundamentally from a Queue?',
      options: [
        'A) Stacks are LIFO (Last-In, First-Out); Queues are FIFO (First-In, First-Out)',
        'B) Stacks allow random indexing; Queues do not',
        'C) Queues operate in O(1) time; Stacks operate in O(N)',
        'D) Stacks cannot store numbers',
      ],
      correctAnswer: 'A) Stacks are LIFO (Last-In, First-Out); Queues are FIFO (First-In, First-Out)',
      explanation: 'Stacks process newest items first (LIFO); Queues process oldest items first (FIFO).',
    },
    {
      id: 'q_stack_9',
      type: 'mcq',
      concept: 'Underflow',
      difficulty: 'Intermediate',
      question: 'What is Stack Underflow?',
      options: [
        'A) Adding items beyond stack capacity',
        'B) Storing negative numbers in a stack',
        'C) Attempting to pop an element from an empty stack',
        'D) Memory corruption in heap',
      ],
      correctAnswer: 'C) Attempting to pop an element from an empty stack',
      explanation: 'Stack Underflow occurs when popping from an empty stack.',
    },
    {
      id: 'q_stack_10',
      type: 'mcq',
      concept: 'Python Syntax',
      difficulty: 'Intermediate',
      question: 'Which array method in Python behaves like push()?',
      options: ['A) list.append(item)', 'B) list.insert(0, item)', 'C) list.extend()', 'D) list.pop(0)'],
      correctAnswer: 'A) list.append(item)',
      explanation: 'list.append(item) adds an item to the end (top) of the list in O(1) time.',
    },
  ],

  matrix: [
    {
      id: 'q_mat_1',
      type: 'mcq',
      concept: 'Multiplication Condition',
      difficulty: 'Intermediate',
      question: 'What is the required condition to multiply matrix A (m×n) by matrix B (p×q)?',
      options: [
        'A) m must equal q',
        'B) n must equal p (columns of A = rows of B)',
        'C) Both matrices must be square',
        'D) m must equal p',
      ],
      correctAnswer: 'B) n must equal p (columns of A = rows of B)',
      explanation: 'Matrix multiplication A × B is valid only when the number of columns in A equals the number of rows in B.',
    },
    {
      id: 'q_mat_2',
      type: 'mcq',
      concept: 'Complexity',
      difficulty: 'Intermediate',
      question: 'What is the Time Complexity of standard N×N Matrix Multiplication?',
      options: ['A) O(N) linear time', 'B) O(N log N)', 'C) O(N^3) cubic time', 'D) O(N^2) quadratic time'],
      correctAnswer: 'C) O(N^3) cubic time',
      explanation: 'Standard matrix multiplication calculates N^2 entries, each taking N multiplications, yielding O(N^3) complexity.',
    },
    {
      id: 'q_mat_3',
      type: 'mcq',
      concept: 'Identity Matrix',
      difficulty: 'Intermediate',
      question: 'What is the Identity Matrix I?',
      options: [
        'A) A matrix filled entirely with 0s',
        'B) A square matrix with 1s on the main diagonal and 0s elsewhere',
        'C) A matrix filled entirely with 1s',
        'D) A matrix with negative values',
      ],
      correctAnswer: 'B) A square matrix with 1s on the main diagonal and 0s elsewhere',
      explanation: 'Multiplying any matrix A by the Identity Matrix I leaves A unchanged: A × I = A.',
    },
    {
      id: 'q_mat_4',
      type: 'mcq',
      concept: 'Determinant',
      difficulty: 'Intermediate',
      question: 'What is the determinant of a 2×2 matrix [[a, b], [c, d]]?',
      options: ['A) ad - bc', 'B) ac - bd', 'C) ab + cd', 'D) ad + bc'],
      correctAnswer: 'A) ad - bc',
      explanation: 'The determinant of a 2x2 matrix [[a, b], [c, d]] is computed as (a*d - b*c).',
    },
    {
      id: 'q_mat_5',
      type: 'mcq',
      concept: 'Dimensions',
      difficulty: 'Intermediate',
      question: 'If matrix A is size 3×2 and matrix B is size 2×4, what is the dimension of result matrix C = A × B?',
      options: ['A) 2×2', 'B) 3×2', 'C) 3×4', 'D) 4×3'],
      correctAnswer: 'C) 3×4',
      explanation: 'Multiplying A (3×2) by B (2×4) produces matrix C of size (3×4).',
    },
    {
      id: 'q_mat_6',
      type: 'mcq',
      concept: 'Commutativity',
      difficulty: 'Intermediate',
      question: 'Is matrix multiplication commutative in general (A × B = B × A)?',
      options: [
        'A) Yes, always',
        'B) No, A × B is generally NOT equal to B × A',
        'C) Only for 2x2 matrices',
        'D) Only for negative matrices',
      ],
      correctAnswer: 'B) No, A × B is generally NOT equal to B × A',
      explanation: 'Matrix multiplication is non-commutative: order matters!',
    },
    {
      id: 'q_mat_7',
      type: 'mcq',
      concept: 'Transpose',
      difficulty: 'Intermediate',
      question: 'What is the transpose of a matrix?',
      options: [
        'A) Swapping rows and columns of the matrix',
        'B) Multiplying every element by -1',
        'C) Inverting all numbers',
        'D) Clearing the main diagonal',
      ],
      correctAnswer: 'A) Swapping rows and columns of the matrix',
      explanation: 'Transposing a matrix swaps rows into columns: entry (i, j) becomes entry (j, i).',
    },
    {
      id: 'q_mat_8',
      type: 'mcq',
      concept: 'Singular Matrix',
      difficulty: 'Intermediate',
      question: 'A matrix with determinant equal to 0 is called:',
      options: ['A) Identity Matrix', 'B) Singular (non-invertible) matrix', 'C) Symmetric matrix', 'D) Orthogonal matrix'],
      correctAnswer: 'B) Singular (non-invertible) matrix',
      explanation: 'If det(A) = 0, matrix A has no inverse and is called singular.',
    },
    {
      id: 'q_mat_9',
      type: 'mcq',
      concept: 'Fast Multiplication',
      difficulty: 'Intermediate',
      question: "Which algorithm reduces N×N matrix multiplication time complexity to O(N^2.81)?",
      options: ["A) Strassen's Algorithm", 'B) Binary Search', 'C) QuickSort', 'D) Dijkstra Algorithm'],
      correctAnswer: "A) Strassen's Algorithm",
      explanation: "Strassen's algorithm uses 7 matrix multiplications instead of 8, achieving O(N^2.81) complexity.",
    },
    {
      id: 'q_mat_10',
      type: 'mcq',
      concept: 'Zero Matrix',
      difficulty: 'Intermediate',
      question: 'What is a Zero Matrix?',
      options: ['A) A matrix with 1s on diagonal', 'B) A matrix with all elements equal to 0', 'C) An empty matrix', 'D) A 1x1 matrix'],
      correctAnswer: 'B) A matrix with all elements equal to 0',
      explanation: 'A zero matrix has every entry equal to 0.',
    },
  ],

  python: [
    {
      id: 'q_py_1',
      type: 'mcq',
      concept: 'Data Structures',
      difficulty: 'Intermediate',
      question: 'Which built-in Python data structure is mutable and ordered?',
      options: ['A) Tuple', 'B) List', 'C) String', 'D) FrozenSet'],
      correctAnswer: 'B) List',
      explanation: 'Lists in Python are mutable (elements can be modified) and ordered by index position.',
    },
    {
      id: 'q_py_2',
      type: 'mcq',
      concept: 'Dictionary Complexity',
      difficulty: 'Intermediate',
      question: 'What is the average Time Complexity of looking up a key in a Python dictionary?',
      options: ['A) O(N) linear time', 'B) O(1) constant time', 'C) O(N^2)', 'D) O(log N)'],
      correctAnswer: 'B) O(1) constant time',
      explanation: 'Python dictionaries use hash tables, providing O(1) average time complexity for key lookups.',
    },
    {
      id: 'q_py_3',
      type: 'mcq',
      concept: 'Syntax',
      difficulty: 'Intermediate',
      question: "What does the 'pass' statement do in Python?",
      options: [
        'A) Exits a loop immediately',
        'B) Acts as a null placeholder that does nothing',
        'C) Skips to the next iteration',
        'D) Raises an exception',
      ],
      correctAnswer: 'B) Acts as a null placeholder that does nothing',
      explanation: 'The pass statement is a syntactical placeholder used when code is required but no action is needed.',
    },
    {
      id: 'q_py_4',
      type: 'mcq',
      concept: 'List Append',
      difficulty: 'Intermediate',
      question: 'Which method adds an element to the end of a Python List in O(1) time?',
      options: ['A) list.append(item)', 'B) list.insert(0, item)', 'C) list.extend()', 'D) list.push(item)'],
      correctAnswer: 'A) list.append(item)',
      explanation: 'list.append(item) adds an item to the end of the list in amortized O(1) time.',
    },
    {
      id: 'q_py_5',
      type: 'mcq',
      concept: 'Tuple vs List',
      difficulty: 'Intermediate',
      question: 'What is the main difference between a Tuple and a List in Python?',
      options: [
        'A) Tuples cannot store strings',
        'B) Lists run faster than tuples',
        'C) Tuples are immutable; Lists are mutable',
        'D) Lists cannot store integers',
      ],
      correctAnswer: 'C) Tuples are immutable; Lists are mutable',
      explanation: 'Tuples cannot be modified after creation, whereas Lists are mutable.',
    },
    {
      id: 'q_py_6',
      type: 'mcq',
      concept: 'Set Complexity',
      difficulty: 'Intermediate',
      question: 'What is the average time complexity of checking membership (`x in set`) in a Python set?',
      options: ['A) O(N)', 'B) O(1) average time', 'C) O(N log N)', 'D) O(N^2)'],
      correctAnswer: 'B) O(1) average time',
      explanation: 'Sets are hash-based structures providing O(1) average membership check.',
    },
    {
      id: 'q_py_7',
      type: 'mcq',
      concept: 'KeyError',
      difficulty: 'Intermediate',
      question: 'What happens when you access a dictionary key that does not exist using `dict[key]`?',
      options: ['A) KeyError is raised', 'B) Returns None silently', 'C) Returns 0', 'D) Appends key to dict'],
      correctAnswer: 'A) KeyError is raised',
      explanation: 'Direct indexing `dict[key]` raises a KeyError if the key is missing. Use `dict.get(key)` to avoid exceptions.',
    },
    {
      id: 'q_py_8',
      type: 'mcq',
      concept: 'Enumerate',
      difficulty: 'Intermediate',
      question: 'Which built-in function yields both index and value when iterating over a list?',
      options: ['A) range()', 'B) enumerate()', 'C) zip()', 'D) map()'],
      correctAnswer: 'B) enumerate()',
      explanation: 'enumerate(iterable) yields (index, value) tuples during iteration.',
    },
    {
      id: 'q_py_9',
      type: 'mcq',
      concept: 'Slicing',
      difficulty: 'Intermediate',
      question: 'What does the slice syntax `arr[::-1]` do on a Python list?',
      options: ['A) Reverses the list', 'B) Sorts in ascending order', 'C) Removes last element', 'D) Duplicates list'],
      correctAnswer: 'A) Reverses the list',
      explanation: '`arr[::-1]` steps backwards through the list, returning a reversed copy.',
    },
    {
      id: 'q_py_10',
      type: 'mcq',
      concept: 'Tuple Traps',
      difficulty: 'Intermediate',
      question: 'What is the output of `type((1,))` in Python?',
      options: ['A) int', 'B) tuple', 'C) list', 'D) set'],
      correctAnswer: 'B) tuple',
      explanation: 'The trailing comma `(1,)` creates a single-element tuple. Without the comma `(1)` is just an integer in parentheses.',
    },
  ],

  ai: [
    {
      id: 'q_ai_1',
      type: 'mcq',
      concept: 'Activation Function',
      difficulty: 'Intermediate',
      question: 'What is the primary role of an Activation Function (e.g. ReLU, Sigmoid) in Neural Networks?',
      options: [
        'A) To speed up file saving',
        'B) To introduce non-linearity, allowing the model to learn complex patterns',
        'C) To set all weights to zero',
        'D) To reduce dataset size',
      ],
      correctAnswer: 'B) To introduce non-linearity, allowing the model to learn complex patterns',
      explanation: 'Without non-linear activation functions, a multi-layer neural network behaves like a single linear regression model.',
    },
    {
      id: 'q_ai_2',
      type: 'mcq',
      concept: 'Backpropagation',
      difficulty: 'Intermediate',
      question: 'Which algorithm updates neural network weights by calculating loss gradients backward?',
      options: [
        'A) Backpropagation with Gradient Descent',
        'B) Binary Search',
        'C) Breadth-First Search',
        'D) Random Search',
      ],
      correctAnswer: 'A) Backpropagation with Gradient Descent',
      explanation: 'Backpropagation uses the calculus chain rule to compute gradients of the loss function with respect to each weight.',
    },
    {
      id: 'q_ai_3',
      type: 'mcq',
      concept: 'Overfitting',
      difficulty: 'Intermediate',
      question: 'What occurs when a model suffers from Overfitting?',
      options: [
        'A) It performs poorly on both training and test data',
        'B) It memorizes training data perfectly but fails to generalize to unseen test data',
        'C) It trains too quickly',
        'D) It runs out of RAM',
      ],
      correctAnswer: 'B) It memorizes training data perfectly but fails to generalize to unseen test data',
      explanation: 'Overfitting happens when a high-capacity model fits noise in the training set rather than underlying rules.',
    },
    {
      id: 'q_ai_4',
      type: 'mcq',
      concept: 'ReLU Formula',
      difficulty: 'Intermediate',
      question: 'What is the mathematical definition of the ReLU activation function?',
      options: ['A) f(x) = max(0, x)', 'B) f(x) = 1 / (1 + e^-x)', 'C) f(x) = x^2', 'D) f(x) = sin(x)'],
      correctAnswer: 'A) f(x) = max(0, x)',
      explanation: 'ReLU (Rectified Linear Unit) outputs x if positive, and 0 otherwise: max(0, x).',
    },
    {
      id: 'q_ai_5',
      type: 'mcq',
      concept: 'Hyperparameters',
      difficulty: 'Intermediate',
      question: 'What is a hyperparameter in Machine Learning?',
      options: [
        'A) A parameter learned automatically during training',
        'B) A hardware specification',
        'C) A configuration set before training (e.g. learning rate, batch size)',
        'D) An output prediction',
      ],
      correctAnswer: 'C) A configuration set before training (e.g. learning rate, batch size)',
      explanation: 'Hyperparameters (like learning rate and batch size) are configured before model training begins.',
    },
    {
      id: 'q_ai_6',
      type: 'mcq',
      concept: 'Loss Function',
      difficulty: 'Intermediate',
      question: 'What component measures how far predictions deviate from actual target values?',
      options: ['A) Optimizer', 'B) Loss / Cost Function', 'C) Learning Rate', 'D) Epoch'],
      correctAnswer: 'B) Loss / Cost Function',
      explanation: 'The loss function quantifies error between model predictions and true ground truth labels.',
    },
    {
      id: 'q_ai_7',
      type: 'mcq',
      concept: 'Dropout',
      difficulty: 'Intermediate',
      question: 'What regularization technique randomly deactivates neurons during training to prevent overfitting?',
      options: ['A) Dropout', 'B) Batch Normalization', 'C) Data Augmentation', 'D) Early Stopping'],
      correctAnswer: 'A) Dropout',
      explanation: 'Dropout randomly zeroes neuron activations during training, forcing redundant feature representations.',
    },
    {
      id: 'q_ai_8',
      type: 'mcq',
      concept: 'Weights',
      difficulty: 'Intermediate',
      question: 'In a neural network, what does a weight represent?',
      options: [
        'A) The file size of the model',
        'B) The strength of connection between two neurons',
        'C) The number of training samples',
        'D) The GPU temperature',
      ],
      correctAnswer: 'B) The strength of connection between two neurons',
      explanation: 'Weights determine how strongly an input signal influences the output of the receiving neuron.',
    },
    {
      id: 'q_ai_9',
      type: 'mcq',
      concept: 'Gradient Descent',
      difficulty: 'Intermediate',
      question: 'What is Gradient Descent?',
      options: [
        'A) A sorting algorithm',
        'B) A hardware accelerator',
        'C) An optimization algorithm that steps in the direction of steepest loss reduction',
        'D) A database indexing method',
      ],
      correctAnswer: 'C) An optimization algorithm that steps in the direction of steepest loss reduction',
      explanation: 'Gradient Descent iteratively updates model parameters opposite to the gradient to reach minimum loss.',
    },
    {
      id: 'q_ai_10',
      type: 'mcq',
      concept: 'Epoch',
      difficulty: 'Intermediate',
      question: 'What is an Epoch in deep learning?',
      options: [
        'A) One full pass of the training dataset through the neural network',
        'B) The time taken for 1 forward pass',
        'C) The total number of layers',
        'D) The final accuracy metric',
      ],
      correctAnswer: 'A) One full pass of the training dataset through the neural network',
      explanation: 'An epoch consists of one complete cycle over all training samples.',
    },
  ],

  recursion: [
    {
      id: 'q_rec_1',
      type: 'mcq',
      concept: 'Base Case Role',
      difficulty: 'Intermediate',
      question: 'What is the primary role of a base case in a recursive function?',
      options: [
        'A) To make code run faster',
        'B) To stop execution and prevent Stack Overflow',
        'C) To initialize global variables',
        'D) To convert loops into functions',
      ],
      correctAnswer: 'B) To stop execution and prevent Stack Overflow',
      explanation: 'The base case provides a non-recursive return path that unwinds the call stack and prevents memory overflow.',
    },
    {
      id: 'q_rec_2',
      type: 'mcq',
      concept: 'Recursion Error',
      difficulty: 'Intermediate',
      question: 'What error occurs in Python if a recursive function lacks a base case?',
      options: [
        'A) RecursionError: maximum recursion depth exceeded',
        'B) MemoryOverflowWarning',
        'C) NullPointerException',
        'D) ZeroDivisionError',
      ],
      correctAnswer: 'A) RecursionError: maximum recursion depth exceeded',
      explanation: 'Python enforces a maximum recursion limit (1000 frames) to protect memory. Exceeding it raises a RecursionError.',
    },
    {
      id: 'q_rec_3',
      type: 'mcq',
      concept: 'Call Stack Allocation',
      difficulty: 'Intermediate',
      question: 'What happens on the Call Stack every time a function calls itself?',
      options: [
        'A) The previous function frame is deleted immediately',
        'B) Heap memory is cleared',
        'C) A new stack frame containing local variables is pushed onto the stack',
        'D) No memory is consumed',
      ],
      correctAnswer: 'C) A new stack frame containing local variables is pushed onto the stack',
      explanation: 'Each recursive invocation pushes a new Stack Frame onto the operating system call stack.',
    },
    {
      id: 'q_rec_4',
      type: 'mcq',
      concept: 'Stack Tracing',
      difficulty: 'Intermediate',
      question: 'In calculating Factorial of 4 recursively `factorial(4)`, how many total frames exist on the stack at the deepest point?',
      options: ['A) 1 frame', 'B) 4 frames (or 5 including base case)', 'C) 16 frames', 'D) 0 frames'],
      correctAnswer: 'B) 4 frames (or 5 including base case)',
      explanation: 'factorial(4) calls factorial(3), which calls factorial(2), which calls factorial(1) — creating stacked frames.',
    },
    {
      id: 'q_rec_5',
      type: 'mcq',
      concept: 'Stack Unwinding',
      difficulty: 'Intermediate',
      question: 'What is stack unwinding in recursion?',
      options: [
        'A) The return phase where function calls finish and pass return values back up the stack',
        'B) Clearing the RAM completely',
        'C) Pushing new frames onto memory',
        'D) Converting recursion into a while loop',
      ],
      correctAnswer: 'A) The return phase where function calls finish and pass return values back up the stack',
      explanation: 'Stack unwinding occurs after hitting the base case as stack frames pop off and pass return values back.',
    },
    {
      id: 'q_rec_6',
      type: 'mcq',
      concept: 'Memoization',
      difficulty: 'Intermediate',
      question: 'What technique optimizes recursive functions by storing previously computed subproblem results?',
      options: ['A) Recursion', 'B) Memoization (Dynamic Programming)', 'C) Garbage Collection', 'D) Backtracking'],
      correctAnswer: 'B) Memoization (Dynamic Programming)',
      explanation: 'Memoization caches results of expensive function calls to avoid recomputing identical subproblems.',
    },
    {
      id: 'q_rec_7',
      type: 'mcq',
      concept: 'Tail Recursion',
      difficulty: 'Intermediate',
      question: 'What is tail recursion?',
      options: [
        'A) Recursion that runs backwards',
        'B) A function with 2 base cases',
        'C) A recursive call where the function call is the final action executed in the function',
        'D) Recursion without return statement',
      ],
      correctAnswer: 'C) A recursive call where the function call is the final action executed in the function',
      explanation: 'In tail recursion, the recursive call is the last executed statement, enabling compiler tail call optimization.',
    },
    {
      id: 'q_rec_8',
      type: 'mcq',
      concept: 'Recursion Limit',
      difficulty: 'Intermediate',
      question: 'What is the default recursion depth limit in standard Python?',
      options: ['A) 1000 frames', 'B) 10 frames', 'C) Unlimited', 'D) 65,536 frames'],
      correctAnswer: 'A) 1000 frames',
      explanation: 'Python sets `sys.getrecursionlimit()` to 1000 by default.',
    },
    {
      id: 'q_rec_9',
      type: 'mcq',
      concept: 'Fibonacci Complexity',
      difficulty: 'Intermediate',
      question: 'In Fibonacci calculation `fib(n) = fib(n-1) + fib(n-2)`, what is the time complexity without memoization?',
      options: ['A) O(N)', 'B) O(N log N)', 'C) O(2^n) exponential time', 'D) O(1)'],
      correctAnswer: 'C) O(2^n) exponential time',
      explanation: 'Naive recursive Fibonacci branches into two subcalls at each step, forming a tree of 2^N operations.',
    },
    {
      id: 'q_rec_10',
      type: 'mcq',
      concept: 'Applications',
      difficulty: 'Intermediate',
      question: 'Which problem domain is naturally solved using recursive tree structures?',
      options: ['A) Array indexing', 'B) Tower of Hanoi & Tree Traversal', 'C) Queue Enqueue', 'D) Hash map lookup'],
      correctAnswer: 'B) Tower of Hanoi & Tree Traversal',
      explanation: 'Hierarchical structures like trees and combinatorial puzzles like Tower of Hanoi are naturally solved recursively.',
    },
  ],

  dsa: [
    {
      id: 'q_dsa_1',
      type: 'mcq',
      concept: 'Merge Sort Complexity',
      difficulty: 'Intermediate',
      question: 'Which sorting algorithm guarantees O(N log N) time complexity in all cases (worst, average, best)?',
      options: ['A) QuickSort', 'B) Merge Sort', 'C) Bubble Sort', 'D) Insertion Sort'],
      correctAnswer: 'B) Merge Sort',
      explanation: 'Merge Sort consistently divides arrays into halves and merges them in O(N log N) time regardless of initial order.',
    },
    {
      id: 'q_dsa_2',
      type: 'mcq',
      concept: 'BFS Traversal',
      difficulty: 'Intermediate',
      question: 'Which data structure is primarily used to implement Breadth-First Search (BFS) graph traversal?',
      options: ['A) Stack (LIFO)', 'B) Queue (FIFO)', 'C) Binary Heap', 'D) Hash Table'],
      correctAnswer: 'B) Queue (FIFO)',
      explanation: 'BFS explores nodes level by level using a First-In, First-Out (FIFO) Queue.',
    },
    {
      id: 'q_dsa_3',
      type: 'mcq',
      concept: 'Binary Search Tree',
      difficulty: 'Intermediate',
      question: 'In a Binary Search Tree (BST), where are keys smaller than the root node stored?',
      options: ['A) In the right subtree', 'B) In the left subtree', 'C) At the leaf level only', 'D) In a random position'],
      correctAnswer: 'B) In the left subtree',
      explanation: 'By BST definition, all nodes in the left subtree have values smaller than the root node.',
    },
    {
      id: 'q_dsa_4',
      type: 'mcq',
      concept: 'Binary Search Condition',
      difficulty: 'Intermediate',
      question: 'What is the prerequisite condition for running Binary Search on an array?',
      options: ['A) The array MUST be sorted', 'B) The array must contain positive numbers only', 'C) The array length must be even', 'D) The array must be a matrix'],
      correctAnswer: 'A) The array MUST be sorted',
      explanation: 'Binary Search relies on dividing a sorted array in half. Unsorted arrays require linear search.',
    },
    {
      id: 'q_dsa_5',
      type: 'mcq',
      concept: 'QuickSort Worst Case',
      difficulty: 'Intermediate',
      question: 'What is the worst-case Time Complexity of QuickSort (e.g. when already sorted with bad pivot choice)?',
      options: ['A) O(N log N)', 'B) O(N)', 'C) O(N^2) quadratic time', 'D) O(1)'],
      correctAnswer: 'C) O(N^2) quadratic time',
      explanation: 'QuickSort degrades to O(N^2) if the pivot choice produces unbalanced 1-element partitions.',
    },
    {
      id: 'q_dsa_6',
      type: 'mcq',
      concept: 'Binary Search Complexity',
      difficulty: 'Intermediate',
      question: 'What is the average Time Complexity of Binary Search?',
      options: ['A) O(N)', 'B) O(log N)', 'C) O(N log N)', 'D) O(1)'],
      correctAnswer: 'B) O(log N)',
      explanation: 'Binary Search halves the remaining search area in each step, taking log2(N) steps.',
    },
    {
      id: 'q_dsa_7',
      type: 'mcq',
      concept: 'In-Place Partitioning',
      difficulty: 'Intermediate',
      question: 'Which sorting algorithm uses pivot partitioning in-place?',
      options: ['A) QuickSort', 'B) Merge Sort', 'C) Counting Sort', 'D) Radix Sort'],
      correctAnswer: 'A) QuickSort',
      explanation: 'QuickSort partitions elements in-place around a pivot element.',
    },
    {
      id: 'q_dsa_8',
      type: 'mcq',
      concept: 'FIFO',
      difficulty: 'Intermediate',
      question: 'What data structure operates on First-In, First-Out (FIFO) principle?',
      options: ['A) Stack', 'B) Queue', 'C) Array', 'D) Heap'],
      correctAnswer: 'B) Queue',
      explanation: 'Queues process items in FIFO order: first enqueued is first dequeued.',
    },
    {
      id: 'q_dsa_9',
      type: 'mcq',
      concept: 'Merge Sort Space',
      difficulty: 'Intermediate',
      question: 'What is the space complexity of standard Merge Sort?',
      options: ['A) O(1)', 'B) O(log N)', 'C) O(N) auxiliary space', 'D) O(N^2)'],
      correctAnswer: 'C) O(N) auxiliary space',
      explanation: 'Merge Sort creates auxiliary arrays of size N during the merge step.',
    },
    {
      id: 'q_dsa_10',
      type: 'mcq',
      concept: 'DFS Traversal',
      difficulty: 'Intermediate',
      question: 'Which graph traversal uses a Stack (or function recursion) under the hood?',
      options: ['A) Depth-First Search (DFS)', 'B) Breadth-First Search (BFS)', 'C) Kruskal Algorithm', 'D) Prim Algorithm'],
      correctAnswer: 'A) Depth-First Search (DFS)',
      explanation: 'DFS explores as deep as possible along branches using a Stack or recursion.',
    },
  ],
};

export function getQuizQuestionsForTopic(topicTitle: string, roundIndex: number = 0, excludeIds: string[] = []): QuizQuestion[] {
  const t = (topicTitle || '').toLowerCase().trim();

  let pool = ALL_QUIZ_POOLS.recursion;
  if (t.includes('stack') || t.includes('lifo')) pool = ALL_QUIZ_POOLS.stack;
  else if (t.includes('matrix') || t.includes('linear')) pool = ALL_QUIZ_POOLS.matrix;
  else if (t.includes('python')) pool = ALL_QUIZ_POOLS.python;
  else if (t.includes('ai') || t.includes('neural')) pool = ALL_QUIZ_POOLS.ai;
  else if (t.includes('sort') || t.includes('search') || t.includes('merge') || t.includes('dsa') || t.includes('tree')) pool = ALL_QUIZ_POOLS.dsa;

  // Exclude previously asked question IDs to prevent duplicates
  const excludeSet = new Set(excludeIds);
  let available = pool.filter((q) => !excludeSet.has(q.id));

  // If we ran out of new questions in the pool, reset available to pool
  if (available.length < 5) {
    available = pool;
  }

  // Calculate slice range for 5 questions per round
  const startIndex = (roundIndex * 5) % available.length;
  let questions = available.slice(startIndex, startIndex + 5);

  // Fallback if slice is smaller than 5
  if (questions.length < 5) {
    questions = [...questions, ...pool.slice(0, 5 - questions.length)];
  }

  return questions;
}
